packages:
  - "."

minimumReleaseAge: 10080 # 7 days
trustPolicy: no-downgrade
blockExoticSubdeps: true

allowBuilds:
  '@google/genai': false
  protobufjs: false
  sharp: true
  unrs-resolver: false

overrides:
  undici-types: "5.26.5"
  eslint-import-resolver-typescript: "3.9.1"
  semver: "7.6.3"
